### ISSUE TITLE
Erro ao alterar data de abertura

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/participe-portal#102]
Ao alterar a data de abertura o sistema não está exibindo a tela de login.
conforme vídeo abaixo abaixo:

https://www.loom.com/share/4aae80b088db438c99171497401eccba

**Comment by vdcordeiro** [comment]
Não está sendo seguida a regra em negrito abaixo, documentada em https://totemti.atlassian.net/wiki/spaces/PARTICIPE/pages/1541701674/Pr+-abertura+1.0:

> Regras
> Campo “Iniciaremos em”:
> O padrão do tempo apresentado será: em dias, horas, minutos e segundos;
> Este é um campo de contagem regressiva. Deve portanto ser atualizado a cada 1 segundo.
> 
> **Se no modo automático, quando a página de pré-abertura estiver aberta e a contagem atingir o valor 0 0 0 0, a página de login (aberta) deve ser exibida automaticamente sobre a atual;**

No modo automático, o portal deve sempre considerar as datas/horas de abertura e encerramento em comparação à data/hora atual para decidir sobre a exibição, e não a flag "pre-abertura | aberta | pos-encerramento". Essa flag só é usada no modo manual.

Não testamos, mas o mesmo problema deve estar ocorrendo na transição de encerramento.
