### ISSUE TITLE
Campo "Desejo receber mensagens..." desabilitado por default

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/participe-portal#105]
O campo "Desejo receber mensagens informativas" está desabilitado por default para usuários recém criados.
A documentação especifica _"Por padrão o campo “Desejo receber mensagens informativas” é apresentado habilitado (ativo);"_

A imagem abaixo mostra a tela Meu Perfil de um usuário recem criado:
![image](https://user-images.githubusercontent.com/41954965/131737038-82148f59-303f-4805-8c8a-ee18e2c68203.png)

**Comment by msantosmarcos** [comment]
demanda executada.
