### ISSUE TITLE
Botões Destacar e Comentar não são exibidos

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/participe-portal#107]
Cenário:
- Estrutura:
  - Sem regionalização;
  - 02 itens de profundidade (Área e Desafio);
  - Em ambos os itens estão selecionados os campos "Destaques" e "Comentários";

No portal, ao exibir os cartões do primeiro nível (Áreas) não aparecem os botões para a realização de "Destaques" nem "Comentários". Os botões aparecem corretamente nos cartões do segundo nível (Desafios).
 
Vídeo:
https://www.loom.com/share/be1cba593b2f452f953d2dfa49751d8c

**Comment by msantosmarcos** [comment]
demanda resolvida.

**Comment by msantosmarcos** [comment]
demanda resolvida
