### ISSUE TITLE
Dashboard apresenta ordem alfabética invertida

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/participe-portal#108]
No painel **da direita**, ao selecionar exibição de ordem alfabética **crescente**, os itens são exibidos em ordem **decrescente** e vice-versa. 
O mesmo bug ocorre na aplicação de administração.
https://www.loom.com/share/0e57999666f84b92bada88d7eff9442e

**Comment by msantosmarcos** [comment]
demanda resolvida.
