### ISSUE TITLE
Lista de seleção de Municípios

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/participe-portal#17]
Na página "Complemente seu Cadastro", a lista de seleção de municípios deve:

1. Ser exibida como uma lista e não um busca, isto é, no lugar do ícone de lupa deve ser um ícone de seta para baixo (v), para sinalizar que o usuário precisa **selecionar** uma opção. 
Utilizar o icone fontawesome `<i class="fas fa-chevron-down"><i>`

2. A lista deve aparecer em ordem alfabética.

O comportamento de busca textual deve ser mantido.

**Comment by vdcordeiro** [comment]
Item 2 corrigido por Vagner Cordeiro.

**Comment by nataliafvilalva** [comment]
Criado ticket PAR-292 no JIRA para correção.
