### ISSUE TITLE
Mensagem de erro vaga na página Complemente seu Cadastro 

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/participe-portal#21]
A mensagem de erro ao digitar o nome errado do município, é muito vaga. Deveria ser mais específica, como "O município informado é inválido."
![image](https://user-images.githubusercontent.com/41954965/86514132-479fbc80-bde6-11ea-9ad0-6071c0657ab4.png)

**Comment by nataliafvilalva** [comment]
Criado ticket PAR-293 no JIRA para correção.
