### ISSUE TITLE
Busca: subitens

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/participe-portal#25]
A busca não está procurando nos subitens, como especificado.
A palava SUS consta em um dos desafios da Área Estratégica Saúde Integral:
![image](https://user-images.githubusercontent.com/41954965/86514784-b1ba6080-bdea-11ea-8f02-62b9070b85d9.png)

Entretanto, a busca a partir da página de seleção da Área Estratégica não traz resultado.
![image](https://user-images.githubusercontent.com/41954965/86514816-fba34680-bdea-11ea-8f27-a0e166ab1ff9.png)

Deveria trazer como resultado [Saúde Integral]

**Comment by nataliafvilalva** [comment]
Criado ticket PAR-295 no JIRA para correção.
