### ISSUE TITLE
Ordenação alfabética falha com acentuação

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/participe-portal#32]
A ordenação alfabética deve considerar os caracteres simples correspondentes no lugar dos caracteres acentuados. No caso da microrregião abaixo, os nomes de municípios iniciados por Á deveriam vir na frente.
![image](https://user-images.githubusercontent.com/41954965/86653141-58555b80-bfbb-11ea-8814-c13dc9a19586.png)

**Comment by nataliafvilalva** [comment]
Criado ticket PAR-274 no JIRA para correção.
