### ISSUE TITLE
Destaques com comentários no lixo não podem ser desfeitos

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/participe-portal#41]
Se o cidadão faz uma proposta e depois o moderador joga essa proposta no lixo, no portal o balão no desafio continua marcando 1 proposta e o destaque não pode ser retirado.
Se a proposta foi mandada para o lixo, ela não deve ser mais contabilizada pelo portal.
https://www.loom.com/share/7238332e42844df58ec84b7d88949261

**Comment by msantosmarcos** [comment]
demanda executada com sucesso.
