### ISSUE TITLE
Mouse pointer na tela de login

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/participe-portal#51]
É padrão em aplicações web e no Participe, que para áreas clicáveis como botões e links, ao se passar o cursor sobre elas a imagem do cursor seja alterada de uma seta (default) para uma mão apontando (pointer). 
Esse comportamento não ocorre em diversos botões da tela de login.

**Comment by nataliafvilalva** [comment]
Criado ticket PAR-275 no JIRA para correção.
