### ISSUE TITLE
Botões de rolagem sem reuniões para rolar

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/participe-portal#52]
Na tela de login do Portal do Cidadão, quando é exibida uma consulta sem reuniões presenciais, os botões de rolagem aparecem na tela, sem função. Nesse caso os botões não deveriam aparecer.
![image](https://user-images.githubusercontent.com/41954965/94180873-0e229e80-fe75-11ea-99e6-a498ca7d11b7.png)

**Comment by nataliafvilalva** [comment]
Criado ticket PAR-278 no JIRA para correção.
