### ISSUE TITLE
Opção de destacar

### ISSUE THREAD

**Issue by felipecsalles** [sep-es-br/participe-portal#55]
![image](https://user-images.githubusercontent.com/71851259/94571630-95418f00-0246-11eb-8a03-4c19e18bb627.png)
A opção de destacar um desafio não está disponível.

**Comment by vdcordeiro** [comment]
Não é um bug. Está correto. Conforme a estrutura de plano utilizada, o desafio não deve ser "Destacável".

![image](https://user-images.githubusercontent.com/41954965/94575514-b310f300-024a-11eb-8f85-b88903132bc7.png)
