### ISSUE TITLE
Páginas autenticadas com erro no console

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/participe-portal#62]
Após a autenticação, todas as páginas apresentam um mesmo erro no console do navegador, ao carregar a página:

![image](https://user-images.githubusercontent.com/41954965/94579976-c1add900-024f-11eb-8aa5-bfa61109b29f.png)

**Comment by nataliafvilalva** [comment]
Criado ticket PAR-284 no JIRA para correção.
