### ISSUE TITLE
Cards do menu "Participar"

### ISSUE THREAD

**Issue by alanrodrigo** [sep-es-br/participe-portal#66]
Altura e largura fixa: 253 x 304px
Titulo: Roboto Black, 30px
Texto: Roboto Regular, 13px
Aumentar mapa conforme protótipo

![image](https://user-images.githubusercontent.com/42146539/94690625-ba95d200-0306-11eb-83ec-33fa6cd6f260.png)

**Comment by nataliafvilalva** [comment]
Criado ticket PAR-284 no JIRA para correção.
