### ISSUE TITLE
Cards menu "Propostas"

### ISSUE THREAD

**Issue by alanrodrigo** [sep-es-br/participe-portal#67]
Alinhamento dos cards a esquerda
Icone "aspas" diferente do prototipo
Fonte do nome do participante: Roboto Black, 13px
Faltou o tempo da publicação
Ícone curtir diferente do protótipo
Cor tamanho e espaçamento dos elementos a direita dos cards diferente do protótipo

![image](https://user-images.githubusercontent.com/42146539/94691795-20368e00-0308-11eb-8d7f-7bc3f8d55672.png)

**Comment by nataliafvilalva** [comment]
Criado ticket PAR-286 no JIRA para correção.
