### ISSUE TITLE
Cards menu "Minhas Participações"

### ISSUE THREAD

**Issue by alanrodrigo** [sep-es-br/participe-portal#68]
Ícone das propostas ficou achatado
Ícone dos destaques diferente do protótipo
Ícone "aspas"
Ícone curtir
Ícone inserir proposta
Tamanho, alinhamento e espaçamento dos elementos dentro dos cards

conforme protótipo

![image](https://user-images.githubusercontent.com/42146539/94692563-0ba6c580-0309-11eb-8c85-f67df60db118.png)

**Comment by nataliafvilalva** [comment]
Criado ticket PAR-281 no JIRA para correção.
