### ISSUE TITLE
Menu participar "Áreas Estratégicas"

### ISSUE THREAD

**Issue by alanrodrigo** [sep-es-br/participe-portal#69]
Tamanho fonte
Tamanho cards
efeito mouse over
faltou "powered by Participe"

Conforme protótipo

![image](https://user-images.githubusercontent.com/42146539/94693791-89b79c00-030a-11eb-884d-8826ea2f0f7d.png)

**Comment by nataliafvilalva** [comment]
Criado ticket PAR-287 no JIRA para correção.
