### ISSUE TITLE
Campo de pesquisa

### ISSUE THREAD

**Issue by alanrodrigo** [sep-es-br/participe-portal#72]
ao realiza uma pesquisa o sistema deve ser capaz de pesquisar também nos elementos que estão no próximo nível, por exemplo posso pesquisar um desafio na pagina das áreas estratégicas, conforme protótipo
![image](https://user-images.githubusercontent.com/42146539/94723776-a9ad8680-032f-11eb-86e9-b84b45c769d0.png)

limpar pesquisa e retornar as informações ao clicar em fechar pesquisa
![image](https://user-images.githubusercontent.com/42146539/94695069-db145b00-030b-11eb-8827-7127ab8dd3f8.png)

ao começar a digitar a pesquisa, a primeira letra digitada não é computada pelo campo (acontece somente na primeira tentativa, depois fica normal, caso atualize a pagina o problema volta acontecer)
![image](https://user-images.githubusercontent.com/42146539/94720016-4cfb9d00-032a-11eb-826d-c70d2d8da90e.png)

o comportamento em todas as paginas deve ser o mesmo da pesquisa do menu "Minhas participações"

**Comment by nataliafvilalva** [comment]
Criado ticket PAR-291 no JIRA para correção.
